# Generated by Django 5.0.4 on 2024-04-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tag_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='homework',
        ),
        migrations.RemoveField(
            model_name='task',
            name='homework',
        ),
    ]
